# Generated by Django 5.2.10 on 2026-02-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('roll_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('enroll_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('father_husband_name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('paper1', models.PositiveIntegerField(blank=True, null=True)),
                ('paper2', models.PositiveIntegerField(blank=True, null=True)),
                ('paper3', models.PositiveIntegerField(blank=True, null=True)),
                ('paper4', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('grand_total', models.PositiveIntegerField()),
                ('avg_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Supplie', 'Supplie')], max_length=10, null=True)),
                ('division', models.CharField(blank=True, choices=[('First Division', 'First Division'), ('Second Division', 'Second Division'), ('Third Division', 'Third Division')], max_length=15, null=True)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('is_admit_card_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='centers.center')),
            ],
        ),
    ]
