# Generated by Django 5.2.10 on 2026-02-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avg_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='division',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_admit_card_published',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='student',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paper1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paper2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paper3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paper4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='result',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total',
        ),
        migrations.AlterField(
            model_name='student',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='centers.center'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='StudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('paper1', models.PositiveIntegerField(blank=True, null=True)),
                ('paper2', models.PositiveIntegerField(blank=True, null=True)),
                ('paper3', models.PositiveIntegerField(blank=True, null=True)),
                ('paper4', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('grand_total', models.PositiveIntegerField(default=0)),
                ('avg_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Supply', 'Supply')], max_length=10, null=True)),
                ('division', models.CharField(blank=True, choices=[('First Division', 'First Division'), ('Second Division', 'Second Division'), ('Third Division', 'Third Division')], max_length=20, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_admit_card_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='students.student')),
            ],
            options={
                'ordering': ['-session'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
