# Generated by Django 5.2.10 on 2026-02-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('students', '0002_remove_student_avg_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, choices=[('First Division', 'First Division'), ('Second Division', 'Second Division'), ('Third Division', 'Third Division')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grand_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_admit_card_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='medium',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='paper1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paper2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paper3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paper4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='result',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Supplie', 'Supplie')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default=2026, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(default='IBTIDAI SAAL AWWAL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='centers.center'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='StudentAcademic',
        ),
    ]
