# Generated by Django 5.2.10 on 2026-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enroll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
