# Generated by Django 5.2.10 on 2026-02-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('students', '0005_alter_student_enroll_no_alter_student_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='center',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.center', to_field='center_id'),
        ),
    ]
