# Generated by Django 5.2.10 on 2026-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_division_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
