# Generated by Django 5.2.10 on 2026-03-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_alter_centeremail_center'),
        ('students', '0008_alter_student_city_alter_student_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='center_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='centers.center'),
        ),
    ]
