# Generated by Django 5.2.10 on 2026-02-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(unique=True)),
                ('center_id', models.CharField(help_text='Unique Center ID', max_length=50, unique=True)),
                ('center_name', models.CharField(help_text='Center Name', max_length=200)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Center',
                'verbose_name_plural': 'Centers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CenterMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(help_text='Contact mobile number', max_length=15)),
                ('is_primary', models.BooleanField(default=False)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_numbers', to='centers.center')),
            ],
        ),
    ]
