# Generated by Django 5.2.10 on 2026-02-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('paper_no', models.CharField(max_length=50)),
                ('session', models.CharField(choices=[('1', 'First Morning'), ('2', 'Second Evening'), ('3', 'Third Morning'), ('4', 'Fourth Evening')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lifafa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('session', models.CharField(choices=[('1', 'First Morning'), ('2', 'Second Evening'), ('3', 'Third Morning'), ('4', 'Fourth Evening')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifafas', to='centers.center')),
                ('papers', models.ManyToManyField(to='centers.paper')),
            ],
        ),
    ]
