# Generated by Django 5.2.10 on 2026-02-20 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_paper_lifafa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifafa',
            name='papers',
        ),
        migrations.AlterModelOptions(
            name='lifafa',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='LifafaPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('paper_no', models.PositiveIntegerField()),
                ('lifafa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='centers.lifafa')),
            ],
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
