# Generated by Django 5.2.10 on 2026-03-02 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_remove_lifafa_papers_alter_lifafa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='email id', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_id', to='centers.center')),
            ],
        ),
    ]
