# Generated by Django 5.2.10 on 2026-03-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_centeremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centeremail',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='centers.center'),
        ),
    ]
